// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrmUw9qYsOAXbYia_k7UOtKMa2aKT99IE',
    appId: '1:1054755416461:android:c9333cc5475367bbdb75c4',
    messagingSenderId: '1054755416461',
    projectId: 'tanglevr',
    databaseURL: 'https://tanglevr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tanglevr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIQzqc3tIko7mUM4aBJuif2rZvIYC_Rj4',
    appId: '1:1054755416461:ios:04b6b91935e25197db75c4',
    messagingSenderId: '1054755416461',
    projectId: 'tanglevr',
    databaseURL: 'https://tanglevr-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tanglevr.appspot.com',
    androidClientId: '1054755416461-9o1eaunj1gq4q6qte047775hslkdsdeh.apps.googleusercontent.com',
    iosClientId: '1054755416461-rg211l6d2fe6ns8maju2kk4ra1v2vj1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.datingApp',
  );
}
